[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "soundscribe"
version = "0.1.1"
description = "Audio transcription CLI tool using faster-whisper"
authors = [
    {name = "Tammy DiPrima", email = "tdiprima@yahoo.com"},
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "faster-whisper>=1.2.1",
    "rich>=14.3.3",
    "rich-argparse>=1.7.1",
]

[project.scripts]
soundscribe = "soundscribe.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["soundscribe"]
